import { Metadata, QuestionClosingMode } from "@models/Metadata.model";
import { Milestone } from "@models/Milestone.model";
import { Repository } from "@models/Repository.model";
import { Session } from "@models/Session.model";
import { NgbTimeStruct } from "@ng-bootstrap/ng-bootstrap";
import { Type } from "class-transformer";
import { GitProviderType } from "@models/GitAuthProvider.model";

/**
 * A practical course, with sessions, questions and
 * milestones (reviews, corrections).
 */
export class Assignment {
  @Type(() => Metadata)
  metadata: Metadata;

  /**
   * The correction milestones
   */
  @Type(() => Milestone)
  corrections: Milestone[];

  /**
   * The practical sessions
   */
  @Type(() => Session)
  sessions: Session[];

  /**
   * The review milestones
   */
  @Type(() => Milestone)
  reviews: Milestone[];

  /**
   * The others milestones. These milestones have no impact on the stats
   * generated by the application, they are just graphical elements
   */
  @Type(() => Milestone)
  others: Milestone[];

  /**
   * The students repositories
   */
  @Type(() => Repository)
  repositories: Repository[];

  id: number;
  instanceHost?: string;
  instanceName?: string;
  uiStatus?: "prepared" | "ongoing" | "finished" | "default";
  provider: GitProviderType = "github";

  constructor() {
    this.metadata = new Metadata();
    this.reviews = [];
    this.corrections = [];
    this.others = [];
    this.sessions = [];
    this.repositories = [];
  }

  get uiType(): GitProviderType {
    return this.provider || "github";
  }

  set uiType(value: GitProviderType) {
    this.provider = value || "github";
  }

  get resolvedInstanceHost(): string {
    if (this.instanceHost) {
      return this.instanceHost;
    }
    if (this.provider === "gitlab") {
      const firstRepoUrl = this.repositories?.[0]?.url;
      if (firstRepoUrl) {
        const sshMatch = firstRepoUrl.match(/^git@([^:]+):/);
        if (sshMatch && sshMatch[1]) {
          return sshMatch[1];
        }
        try {
          return new URL(firstRepoUrl).hostname;
        } catch {
          // ignore invalid url
        }
      }
      return "gitlab.com";
    }
    return "github.com";
  }

  get title(): string {
    return this.metadata.title;
  }

  set title(title: string) {
    this.metadata.title = title;
  }

  get startDate(): string {
    return this.metadata.startDate;
  }

  set startDate(startDate: string) {
    this.metadata.startDate = startDate;
  }

  get endDate(): string {
    return this.metadata.endDate;
  }

  set endDate(endDate: string) {
    this.metadata.endDate = endDate;
  }

  get course(): string {
    return this.metadata.course;
  }

  set course(course: string) {
    this.metadata.course = course;
  }

  get program(): string {
    return this.metadata.program;
  }

  set program(program: string) {
    this.metadata.program = program;
  }

  get year(): string {
    return this.metadata.year;
  }

  set year(year: string) {
    this.metadata.year = year;
  }

  get questions(): string[] {
    return this.metadata.questions;
  }

  set questions(questions: string[]) {
    this.metadata.questions = questions;
  }

  get lastModificationDate(): Date {
    return this.metadata.lastModificationDate;
  }

  set lastModificationDate(lastModificationDate: Date) {
    this.metadata.lastModificationDate = lastModificationDate;
  }

  get defaultSessionDuration(): NgbTimeStruct {
    return this.metadata.defaultSessionDuration;
  }

  set defaultSessionDuration(defaultSessionDuration: NgbTimeStruct) {
    this.metadata.defaultSessionDuration = defaultSessionDuration;
  }

  get closingMode(): QuestionClosingMode {
    return this.metadata?.resolvedClosingMode || "standard";
  }

  set closingMode(closingMode: QuestionClosingMode) {
    if (this.metadata) {
      this.metadata.closingMode = closingMode;
    }
  }

  get customClosingKeywords(): string[] {
    return this.metadata?.resolvedCustomClosingKeywords || [];
  }

  set customClosingKeywords(customClosingKeywords: string[]) {
    if (this.metadata) {
      this.metadata.customClosingKeywords = customClosingKeywords;
    }
  }
}
