import { Milestone } from "@models/Milestone.model";
import { Repository } from "@models/Repository.model";
import { Session } from "@models/Session.model";

export class Assignment {
  /**
   * The document title
   */
  title: string;

  /**
   * The correction milestones
   */
  corrections: Milestone[];

  /**
   * The practical sessions
   */
  sessions: Session[];

  /**
   * The review milestones
   */
  reviews: Milestone[];

  /**
   * The others milestones. These milestones have no impact on the stats generated by the application, they are just graphical elements
   */
  others: Milestone[];

  /**
   * The repositories
   */
  repositories: Repository[];

  /**
   * A date before which commits are not retrieved from Github
   */
  startDate: string;

  /**
   * A date after which commits are not retrieved from Github
   */
  endDate: string;

  /**
   * The course associated with the configuration file
   */
  course: string;

  /**
   * The program associated with the configuration file
   */
  program: string;

  /**
   * The year associated with the configuration file
   */
  year: string;

  /**
   * The questions that will be handled by the application
   */
  questions: string[];

  constructor() {
    this.questions = [];
    this.reviews = [];
    this.corrections = [];
    this.others = [];
    this.sessions = [];
    this.repositories = [];
  }
}
