name: Deploy staging (label)
on:
  pull_request:
    branches: [master]
    types: [labeled]
jobs:
  build:
    if: ${{ github.event.label.name == 'deploy-staging' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "14.X"
      - name: Install Dependencies
        run: yarn --ignore-engines
      - name: Build app
        run: yarn run build-prod
      - name: Upload Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist-git4school
          path: dist/git4school
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Production Artifact
        uses: actions/download-artifact@master
        with:
          name: dist-git4school
          path: dist/git4school
      - name: Deploy staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GIT4SCHOOL }}
          projectId: git4school
          channelId: 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'
