name: Deploy staging (comment)
on:
  issue_comment:
    types: [created, edited]
jobs:
  build:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/deploy') }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/merge"
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "14.X"
      - name: Install Dependencies
        run: yarn --ignore-engines
      - name: Build app
        run: yarn run build-prod
      - name: Upload Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist-git4school
          path: dist/git4school
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/merge"
      - name: Download Production Artifact
        uses: actions/download-artifact@master
        with:
          name: dist-git4school
          path: dist/git4school
      - name: Deploy staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GIT4SCHOOL }}
          projectId: git4school
          channelId: 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'
  comment-staging-link:
    name: Comment staging link in PR comment
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Staging deployed on https://git4school-staging.firebaseapp.com/'
            })
