name: Deploy staging (label)
on:
  pull_request:
    branches: [master]
    types: [labeled]
jobs:
  build:
    if: ${{ github.event.label.name == 'deploy-staging' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "14.X"
      - name: Install Dependencies
        run: yarn --ignore-engines
      - name: Build app
        run: yarn run build-prod
      - name: Upload Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist-git4school
          path: dist/git4school
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Production Artifact
        uses: actions/download-artifact@master
        with:
          name: dist-git4school
          path: dist/git4school
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  comment-staging-link:
    name: Comment staging link in PR comment
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'deploy-staging'
            })
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Staging deployed on https://git4school-staging.firebaseapp.com/'
            })
