name: Deploy production & technical documentation
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build application & technical documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "14.X"
      - name: Install Dependencies
        run: yarn --ignore-engines
      - name: Build app & doc
        run: yarn run build:doc
      - name: Upload Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist-git4school
          path: dist/git4school
      - name: Upload Technical Documentation Artifact
        uses: actions/upload-artifact@master
        with:
          name: tech-docs
          path: tech-docs
  deploy-app:
    name: Deploy application
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Production Artifact
        uses: actions/download-artifact@master
        with:
          name: dist-git4school
          path: dist/git4school
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy-tech-doc:
    name: Deploy technical documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Download Technical Documentation Artifact
        uses: actions/download-artifact@master
        with:
          name: tech-docs
          path: tech-docs
      - name: Pushes technical docs to gh-pages branch
        uses: cpina/github-action-push-to-another-repository@master
        env:
          # F0urchette personal access token
          API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          source-directory: "tech-docs"
          target-branch: gh-pages
          destination-github-username: "git4school"
          destination-repository-name: "git4school-visu"
          user-email: "tech@doc.fr"
          commit-message: ":rocket: Technical documentation"
