name: Push user documentation to the organization repository
on: 
  push:
    branches:
      - master
    paths:
      - "user-docs/**"
jobs:
  deploy-user-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pushes user docs to organization repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          # F0urchette personal access token
          API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          source-directory: 'user-docs'
          target-branch: gh-pages
          destination-github-username: 'git4school'
          destination-repository-name: 'git4school.github.io'
          user-email: user-doc@cd.fr
